### ISSUE TITLE
HuBERT integration available?

### ISSUE THREAD

**Issue by DuyguA** [huggingface/optimum-graphcore#325]
When I try training HubertForCTC, I get the following error from IPUTrainer:

```
KeyError: 'HubertForCTC pipelined version not found in registry.'
```

**Comment by jimypbr** [comment]
Hi! We don't currently support `HubertForCTC`. It's not currently on our roadmap because we haven't had a request for it. We do support `Wav2vec2ForCTC`. https://github.com/huggingface/optimum-graphcore/blob/main/optimum/graphcore/models/wav2vec2/modeling_wav2vec2.py#L370
Wav2vec2 and Hubert are very similar models. It might therefore be quite straightforward to add it, copying what was done for wav2vec2.

**Comment by jimypbr** [comment]
Turns out the code to port Hubert was identical to what we already had for wav2vec2. I added support for it in this PR: https://github.com/huggingface/optimum-graphcore/pull/347

**Comment by DuyguA** [comment]
Sounds great, huge thanks!

**Comment by jimypbr** [comment]
merged onto main branch
